defmodule AgentCore.TestAssessment.AssessmentReport do
  @moduledoc """
  Represents the comprehensive assessment report generated by the system.
  """

  @derive Jason.Encoder

  alias AgentCore.TestAssessment.{
    ReportSummary,
    TestCategory,
    RedundancyFinding,
    CoverageGap,
    ConfigIssue,
    Recommendation
  }

  @type t :: %__MODULE__{
    summary: ReportSummary.t(),
    test_categories: %{String.t() => TestCategory.t()},
    redundancy_findings: [RedundancyFinding.t()],
    coverage_gaps: [CoverageGap.t()],
    config_issues: [ConfigIssue.t()],
    recommendations: [Recommendation.t()],
    phoenix_analysis: map(),
    generated_at: DateTime.t()
  }

  defstruct [
    :summary,
    :test_categories,
    :redundancy_findings,
    :coverage_gaps,
    :config_issues,
    :recommendations,
    :phoenix_analysis,
    :generated_at
  ]
end
