defmodule AgentCore.WorkflowEngine.RagConversationWorkflow.RetrieveContextStep do
  @moduledoc """
  Step to retrieve relevant conversation history using vector database integration.

  This step executes generated queries against the conversation history vector database
  to retrieve semantically similar content. It integrates with the existing vector
  database infrastructure and provides semantic similarity scoring and context ranking.

  ## Input

  Expects `ctx.artifacts[:history_query]` containing the query string generated by
  the previous step, along with conversation context from the workflow input.

  ## Output

  Sets `ctx.artifacts[:retrieved_context]` with a list of relevant conversation
  history items, each containing:
  - `content` - The message content
  - `score` - Similarity score (0.0 to 1.0)
  - `metadata` - Additional metadata (timestamp, message_id, etc.)

  ## Vector Database Integration

  This step integrates with the existing AgentInfra.StoreEcto.MemoryChunkStore
  for vector similarity search without dependencies on plan system modules.
  It uses the AgentRuntime.Llm.Executor for embedding generation.

  ## Error Handling

  Handles empty results gracefully and provides search optimization through
  configurable similarity thresholds and result limits.
  """

  @behaviour AgentCore.WorkflowEngine.Step

  require Logger

  # Default configuration
  @default_limit 10
  @default_threshold 0.7
  @default_embeddings_profile_id "embeddings_nomic_v15"
  @secondary_embeddings_profile_id "embeddings_openai_v3"

  @impl true
  def id, do: :retrieve_context

  @impl true
  def run(ctx, input, opts) do
    # Get the history query from context
    history_query = AgentCore.WorkflowEngine.Context.get_artifact(ctx, :history_query)

    if is_nil(history_query) do
      # If no query, set empty context and continue
      updated_ctx = AgentCore.WorkflowEngine.Context.put_artifact(ctx, :retrieved_context, [])

      output = %{
        retrieved_count: 0,
        reason: "no_history_query",
        query_used: nil
      }

      {:ok, updated_ctx, output}
    else
      conversation_id = Map.get(input, :conversation_id)
      # Don't use input.profile - use embedding profile from opts instead
      embedding_profile_id = determine_embedding_profile_from_opts(opts)
      overrides = Map.get(input, :overrides, %{})

      Logger.debug("[RetrieveContextStep] Starting retrieval with query: #{inspect(history_query)}")
      Logger.debug("[RetrieveContextStep] Embedding profile: #{inspect(embedding_profile_id)}, Overrides: #{inspect(overrides)}")
      Logger.debug("[RetrieveContextStep] Input keys: #{inspect(Map.keys(input))}")
      Logger.debug("[RetrieveContextStep] Input.profile: #{inspect(Map.get(input, :profile))}")

      # Check if vector database infrastructure is available
      if vector_db_available?() do
        case retrieve_conversation_context(history_query, conversation_id, embedding_profile_id, overrides, opts) do
          {:ok, context_items} ->
            updated_ctx =
              AgentCore.WorkflowEngine.Context.put_artifact(ctx, :retrieved_context, context_items)

            output = %{
              retrieved_count: length(context_items),
              query_used: history_query,
              conversation_id: conversation_id,
              top_score: get_top_score(context_items)
            }

            Logger.debug("[RetrieveContextStep] Successfully retrieved #{length(context_items)} context items")
            {:ok, updated_ctx, output}

          {:error, reason} ->
            Logger.warning("[RetrieveContextStep] retrieve_context failed: #{inspect(reason)}")

            # Set empty context on error and continue
            updated_ctx = AgentCore.WorkflowEngine.Context.put_artifact(ctx, :retrieved_context, [])

            output = %{
              retrieved_count: 0,
              error: reason,
              query_used: history_query,
              conversation_id: conversation_id
            }

            {:ok, updated_ctx, output}
        end
      else
        # Vector database not available, skip retrieval but continue workflow
        Logger.info("[RetrieveContextStep] Vector database infrastructure not available, skipping retrieval")

        updated_ctx = AgentCore.WorkflowEngine.Context.put_artifact(ctx, :retrieved_context, [])

        output = %{
          retrieved_count: 0,
          reason: "vector_db_unavailable",
          query_used: history_query,
          conversation_id: conversation_id
        }

        {:ok, updated_ctx, output}
      end
    end
  end

  # Retrieve conversation context using vector database search
  defp retrieve_conversation_context(query, conversation_id, embedding_profile_id, overrides, opts) do
    Logger.debug("[RetrieveContextStep] Generating embedding for query: #{String.slice(query, 0, 100)}...")

    case generate_query_embedding(query, embedding_profile_id, overrides) do
      {:ok, query_embedding} ->
        Logger.debug("[RetrieveContextStep] Successfully generated embedding with profile #{embedding_profile_id}, searching vector database...")

        case search_vector_database(query_embedding, conversation_id, opts) do
          {:ok, memory_chunks} ->
            # Convert memory chunks to context items
            context_items = convert_chunks_to_context(memory_chunks)
            Logger.debug("[RetrieveContextStep] Successfully converted #{length(memory_chunks)} chunks to context items")
            {:ok, context_items}

          {:error, reason} ->
            Logger.warning("[RetrieveContextStep] Vector database search failed: #{inspect(reason)}")
            {:error, reason}
        end

      {:error, reason} ->
        Logger.warning("[RetrieveContextStep] Embedding generation failed with profile #{embedding_profile_id}: #{inspect(reason)}")

        # Try fallback to secondary profile if primary failed
        case try_fallback_embedding_profile(query, embedding_profile_id, overrides, opts) do
          {:ok, query_embedding, fallback_profile} ->
            Logger.info("[RetrieveContextStep] Successfully generated embedding with fallback profile #{fallback_profile}")

            case search_vector_database(query_embedding, conversation_id, opts) do
              {:ok, memory_chunks} ->
                context_items = convert_chunks_to_context(memory_chunks)
                {:ok, context_items}

              {:error, search_reason} ->
                Logger.warning("[RetrieveContextStep] Vector database search failed with fallback profile: #{inspect(search_reason)}")
                {:error, search_reason}
            end

          {:error, fallback_reason} ->
            Logger.error("[RetrieveContextStep] Both primary and fallback embedding profiles failed: #{inspect(fallback_reason)}")
            {:error, {:all_embedding_profiles_failed, %{primary: reason, fallback: fallback_reason}}}
        end
    end
  end

  # Generate embedding for the query text
  defp generate_query_embedding(query, embedding_profile_id, overrides) when is_binary(embedding_profile_id) do
    # Build execution metadata
    exec_meta = %{
      "phase" => "retrieve_context_embedding"
    }

    # Use the embedding profile ID directly - the Executor will resolve it
    embed_profile = embedding_profile_id

    # For embedding operations, we should use minimal overrides to avoid conflicts
    # Only include known safe override keys for embedding operations
    safe_override_keys = [
      "temperature", :temperature,
      "max_tokens", :max_tokens,
      "timeout", :timeout,
      "seed", :seed
    ]

    # Filter out any keys that might conflict with embedding operations
    # Specifically exclude "id" and :id which are used for profile identification
    unsafe_keys = ["id", :id, "profile_id", :profile_id]

    clean_overrides =
      (overrides || %{})
      |> Enum.reject(fn {key, _value} ->
        key in unsafe_keys
      end)
      |> Enum.filter(fn {key, _value} ->
        key in safe_override_keys
      end)
      |> Map.new()

    Logger.debug("[RetrieveContextStep] Using clean overrides for embedding: #{inspect(clean_overrides)}")
    Logger.debug("[RetrieveContextStep] Original overrides: #{inspect(overrides)}")
    Logger.debug("[RetrieveContextStep] Embed profile: #{inspect(embed_profile)}")

    # Check if the Executor module exists and has the embed function
    try do
      # Use the keyword API which handles profile resolution internally
      case AgentRuntime.Llm.Executor.embed(
        profile_id: embedding_profile_id,
        input: query,
        overrides: clean_overrides,
        exec_meta: exec_meta
      ) do
        {:ok, embedding} ->
          # The keyword API returns the embedding directly
          {:ok, embedding}

        {:error, reason} ->
          # Check if the error is due to profile not found and try fallback
          error_string = inspect(reason)
          if String.contains?(error_string, "LLMProfile not found") do
            Logger.warning("[RetrieveContextStep] Embedding profile #{embedding_profile_id} not found, falling back to req_llm")
            # Fall back to the main profile (req_llm) for embedding
            fallback_profile_id = "req_llm"

            case AgentRuntime.Llm.Executor.embed(
              profile_id: fallback_profile_id,
              input: query,
              overrides: clean_overrides,
              exec_meta: exec_meta
            ) do
              {:ok, embedding} ->
                Logger.info("[RetrieveContextStep] Successfully generated embedding with fallback profile #{fallback_profile_id}")
                {:ok, embedding}

              {:error, fallback_reason} ->
                Logger.error("[RetrieveContextStep] Fallback embedding also failed: #{inspect(fallback_reason)}")
                {:error, {:embedding_failed, fallback_reason}}
            end
          else
            {:error, {:embedding_failed, reason}}
          end

        other ->
          {:error, {:unexpected_embedding_result, other}}
      end
    rescue
      UndefinedFunctionError ->
        Logger.info("[RetrieveContextStep] Embedding service not available, skipping vector search")
        {:error, :embedding_service_unavailable}
    end
  end

  defp generate_query_embedding(_query, _profile, _overrides) do
    {:error, :no_profile}
  end

  # Extract embedding vector from the LLM response
  defp extract_embedding_from_response(response) do
    case response.raw do
      %{data: data} when is_list(data) ->
        case data do
          [%{embedding: embedding} | _] when is_list(embedding) -> {:ok, embedding}
          _ -> {:error, :no_embedding_in_response}
        end

      %{"data" => data} when is_list(data) ->
        case data do
          [%{"embedding" => embedding} | _] when is_list(embedding) -> {:ok, embedding}
          _ -> {:error, :no_embedding_in_response}
        end

      _ ->
        {:error, :invalid_response_format}
    end
  end

  # Search the vector database using the query embedding
  defp search_vector_database(query_embedding, conversation_id, opts) do
    # Get search parameters from options
    limit = Map.get(opts, :limit, @default_limit)
    threshold = Map.get(opts, :threshold, @default_threshold)

    # Build search options
    search_opts = [
      limit: limit,
      threshold: threshold
    ]

    # Add conversation filter if provided
    search_opts =
      if conversation_id do
        Keyword.put(search_opts, :conversation_id, conversation_id)
      else
        search_opts
      end

    # Check if the MemoryChunkStore module exists and has the similarity_search function
    try do
      # Execute vector similarity search
      case AgentInfra.StoreEcto.MemoryChunkStore.similarity_search(query_embedding, search_opts) do
        {:ok, chunks} when is_list(chunks) ->
          {:ok, chunks}

        {:error, reason} ->
          {:error, {:vector_search_failed, reason}}

        other ->
          {:error, {:unexpected_search_result, other}}
      end
    rescue
      UndefinedFunctionError ->
        Logger.info("[RetrieveContextStep] Vector database not available, returning empty results")
        {:ok, []}
    end
  end

  # Convert memory chunks to context items with similarity scores
  defp convert_chunks_to_context(memory_chunks) do
    memory_chunks
    |> Enum.map(fn chunk ->
      # Calculate similarity score from distance (pgvector uses cosine distance)
      # Distance is 0-2, where 0 is identical and 2 is opposite
      # Convert to similarity score 0-1 where 1 is most similar
      similarity_score = calculate_similarity_score(chunk)

      %{
        content: chunk.chunk_text,
        score: similarity_score,
        metadata: %{
          chunk_id: chunk.id,
          conversation_id: chunk.conversation_id,
          timestamp: chunk.inserted_at,
          source_message_ids: chunk.source_message_ids,
          token_count: chunk.token_count,
          chunk_metadata: chunk.metadata
        }
      }
    end)
    |> Enum.sort_by(& &1.score, :desc)
  end

  # Calculate similarity score from memory chunk
  # Note: The actual distance calculation is handled by PostgreSQL/pgvector
  # Here we provide a normalized score based on the returned order
  defp calculate_similarity_score(chunk) do
    # Since chunks are returned ordered by similarity from pgvector,
    # we can use a simple scoring mechanism or extract from metadata if available
    # For now, we'll use a base score that decreases with position
    # In a real implementation, you might extract the actual distance from the query

    # Check if the chunk has similarity metadata
    case Map.get(chunk.metadata || %{}, "similarity_score") do
      score when is_number(score) ->
        # Ensure score is between 0 and 1
        max(0.0, min(1.0, score))

      _ ->
        # Default scoring based on the fact that results are ordered by similarity
        # This is a fallback - in practice, you'd want to capture the actual distance
        0.8
    end
  end

  # Get the top similarity score from context items
  defp get_top_score([]), do: nil

  defp get_top_score(context_items) do
    context_items
    |> Enum.map(& &1.score)
    |> Enum.max()
  end

  # Determine which embedding profile to use from step options only
  defp determine_embedding_profile_from_opts(opts) do
    # Try to get the embedding profile from options, fall back to default
    embedding_profile_id = Map.get(opts, :embeddings_profile_id, @default_embeddings_profile_id)

    # If the embedding profile doesn't exist, we'll handle it in the embedding function
    # by catching the "LLMProfile not found" error and falling back
    embedding_profile_id
  end

  # Try fallback embedding profile if primary fails
  defp try_fallback_embedding_profile(query, failed_profile, overrides, opts) do
    # Determine fallback profile
    fallback_profile = cond do
      # If we failed with the primary, try secondary from options
      failed_profile == Map.get(opts, :embeddings_profile_id, @default_embeddings_profile_id) ->
        Map.get(opts, :embeddings_profile_id_secondary, @secondary_embeddings_profile_id)

      # If we failed with secondary, try primary
      failed_profile == Map.get(opts, :embeddings_profile_id_secondary, @secondary_embeddings_profile_id) ->
        Map.get(opts, :embeddings_profile_id, @default_embeddings_profile_id)

      # If we failed with some other profile, try default primary
      true -> @default_embeddings_profile_id
    end

    # Don't retry with the same profile that just failed
    if fallback_profile == failed_profile do
      {:error, :no_fallback_profile_available}
    else
      case generate_query_embedding(query, fallback_profile, overrides) do
        {:ok, embedding} -> {:ok, embedding, fallback_profile}
        {:error, reason} -> {:error, reason}
      end
    end
  end

  # Check if vector database infrastructure is available
  defp vector_db_available? do
    # Check if required modules exist and are loaded
    embedding_available = Code.ensure_loaded?(AgentRuntime.Llm.Executor) and
                         function_exported?(AgentRuntime.Llm.Executor, :embed, 4)

    vector_store_available = Code.ensure_loaded?(AgentInfra.StoreEcto.MemoryChunkStore) and
                            function_exported?(AgentInfra.StoreEcto.MemoryChunkStore, :similarity_search, 2)

    embedding_available and vector_store_available
  end
end
